name = "r2-upload-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# R2 Bucket Binding (no credentials needed!)
[[r2_buckets]]
binding = "PAIRAP_MEDIA"
bucket_name = "pairap-media"

# Use workers.dev subdomain for testing
workers_dev = true

# For production with custom domain, uncomment and configure:
# [env.production]
# routes = [
#   { pattern = "upload.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
